dependencies {
    compileOnly 'org.jetbrains:annotations:26.0.+'
    annotationProcessor 'org.jetbrains:annotations:26.0.+'

    compileOnly 'org.projectlombok:lombok:1.18.+'
    annotationProcessor 'org.projectlombok:lombok:1.18.+'

    annotationProcessor 'org.spongepowered:mixin:0.8.7:processor'

    // Registrate
    implementation jarJar(versions.registrate.get())

    // EMI
    compileOnly versions.emi.get()
    localRuntime versions.emi.get()

    // Jade
    compileOnly versions.jade.get()
    localRuntime versions.jade.get()

    // TFC
    compileOnly versions.patchouli.get()
    localRuntime versions.patchouli.get()
    compileOnly versions.tfc.get()
    localRuntime versions.tfc.get()

    // Etheria
    compileOnly versions.etheria.get()
    localRuntime versions.etheria.get()
}