dependencies {
    compileOnly 'org.jetbrains:annotations:26.0.+'
    annotationProcessor 'org.jetbrains:annotations:26.0.+'

    compileOnly 'org.projectlombok:lombok:1.18.+'
    annotationProcessor 'org.projectlombok:lombok:1.18.+'

    annotationProcessor 'org.spongepowered:mixin:0.8.7:processor'

    // Registrate
    implementation jarJar(versions.registrate.get())

    // EMI
    compileOnly versions.emi.get()
    localRuntime versions.emi.get()

    // Jade
    compileOnly versions.jade.get()
    localRuntime versions.jade.get()

    // TFC
    compileOnly versions.patchouli.get()
    localRuntime versions.patchouli.get()
    compileOnly versions.tfc.get()
    localRuntime versions.tfc.get()

    // AFC
    compileOnly versions.afc.get()
    localRuntime versions.afc.get()

    // Firmalife
    // compileOnly versions.firmalife.get()
    // localRuntime versions.firmalife.get()

    // Kaleidoscope Cookery
    // compileOnly versions.kaleidoscopecookery.get()
    // localRuntime versions.kaleidoscopecookery.get()

    // Etheria
    compileOnly versions.etheria.get()
    localRuntime versions.etheria.get()

    // Totemic
    compileOnly versions.totemic.get()
    localRuntime versions.totemic.get()

    // Hexalia
    compileOnly versions.hexalia.get()
    localRuntime versions.hexalia.get()

    // Enchanted
    compileOnly versions.enchanted.get()
    localRuntime versions.enchanted.get()

    // Hexerei
    compileOnly versions.hexerei.get()
    localRuntime versions.hexerei.get()

    // Eidolon Repraised

    compileOnly versions.eidolon.get()
    localRuntime versions.eidolon.get()

    // OTHER MOD DEPENDENCIES
    localRuntime versions.modopedia.get()
    localRuntime versions.geckolib.get()
    localRuntime versions.stateobserver.get()
}