repositories {
    mavenLocal()
    mavenCentral()
    // force gradle to download FastUtil & LWJGL from the central maven so we can get source artifacts
    exclusiveContent { // Force
        forRepository { mavenCentral() }
        filter {
            includeGroup("it.unimi.dsi")
            //includeGroup("org.lwjgl")
        }
    }

    exclusiveContent { // Modrinth Maven
        forRepository { maven { url = "https://api.modrinth.com/maven/" } }
        filter { includeGroup("maven.modrinth") }
    }
    exclusiveContent { // Curseforge Maven
        forRepository { maven { url = "https://cursemaven.com/" } }
        filter { includeGroup("curse.maven") }
    }

    maven {
        name "Tterrag"
        url "https://mvn.devos.one/snapshots/"
        content {
            includeGroup("com.tterrag.registrate")
        }
    }
    maven {
        name "TerraformersMC"
        url "https://maven.terraformersmc.com/"
    }
}
